### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by lilywub** [tian1327/flsim_dqn#2]
Hi, thank you so much for adding a DQN server on top of Hao Wang's work! I believe that's lots of effort. 

I am still trying to understand the workflow in this set of code and I got confused about the following configs:
        "trained_model": "output/dqn_models/dqn_10-100_model_174.h5",
        "pca_model": "output/dqn_models/pca_10-100.pkl"  

Where can I get the pre-trained model from? Do they get generated before they are used in the code? There is no such folder/file in the 'output' directory. 

Thank you so much!

**Comment by tian1327** [comment]
Thanks for the interest and question! The DQN model needs to be trained before being loaded again for testing on device selection. Therefore, the `trained_model` is the saved best trained DQN model. You can start the `DQNTrain server` by setting the config file option `"server": "dqntrain"` to obtain the best weights. You can refer to `/dqn_noniid_2_10.json` for this training setting.
